// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ShoppingListdotNetAPI2.Models;

#nullable disable

namespace ShoppingListdotNetAPI2.Migrations
{
    [DbContext(typeof(ShoppingListContext))]
    [Migration("20240704191134_initial create")]
    partial class initialcreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ShoppingListdotNetAPI2.Models.ShoppingListItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsPickedUp")
                        .HasColumnType("bit");

                    b.Property<string>("Item")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("ShoppingListItems");

                    b.HasData(
                        new
                        {
                            Id = new Guid("afe8c295-69a5-4bcb-999d-f77cb2825b3d"),
                            CreatedAt = new DateTime(2024, 7, 4, 15, 11, 33, 43, DateTimeKind.Local).AddTicks(2520),
                            IsPickedUp = false,
                            Item = "Milk"
                        },
                        new
                        {
                            Id = new Guid("e0f51482-b9e6-475e-b079-091bde7e99bf"),
                            CreatedAt = new DateTime(2024, 7, 4, 15, 11, 33, 43, DateTimeKind.Local).AddTicks(2532),
                            IsPickedUp = false,
                            Item = "Sandwiches"
                        },
                        new
                        {
                            Id = new Guid("9f7fb0cf-4601-415b-9a12-1c00cb4054ea"),
                            CreatedAt = new DateTime(2024, 7, 4, 15, 11, 33, 43, DateTimeKind.Local).AddTicks(2537),
                            IsPickedUp = false,
                            Item = "Eggs"
                        },
                        new
                        {
                            Id = new Guid("7ed75077-a8f9-4707-9d69-3d1f7c99ee7e"),
                            CreatedAt = new DateTime(2024, 7, 4, 15, 11, 33, 43, DateTimeKind.Local).AddTicks(2542),
                            IsPickedUp = false,
                            Item = "Flour"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
